version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 10000:5000
    networks:
      lab-network:
        ipv4_address: 10.5.0.10
    volumes:
      - ./backend/db.json:/app/db.json:ro

  api-server-1:
    container_name: api-server-1
    image: api-server
    build:
      context: ./apiserver
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    networks:
      lab-network:
        ipv4_address: 10.5.0.11

  api-server-2:
    container_name: api-server-2
    image: api-server
    build:
      context: ./apiserver
      dockerfile: Dockerfile
    ports:
      - 5002:5000
    networks:
      lab-network:
        ipv4_address: 10.5.0.12

  nginx:
    container_name: nginx
    image: nginx-api-steering
    build:
      context: ./nginx
      dockerfile: Dockerfile
      secrets:
        - nginx-crt
        - nginx-key
    ports:
      # Clients access to published REST API
      - 10080:80
      # Admin access to NGINX Plus API and Dashboard
      - 20080:8080
    networks:
      lab-network:
        ipv4_address: 10.5.0.20
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf:ro
      - ./nginx/steering.js:/etc/nginx/conf.d/steering.js:ro
      - ./nginx/steering.conf:/etc/nginx/conf.d/steering.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro

secrets:
  nginx-crt:
    name: nginx-crt
    file: ${NGINX_CERT}
  nginx-key:
    name: nginx-key
    file: ${NGINX_KEY}

networks:
  lab-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
